# Titulos
## Subtitulos
### Subsubtitulos

- Lista
- listas

1.
2.

# Ejecutar comandos desde jupyther notebooks


In [59]:
%%writefile ejemplo.txt
Hola a todos

Overwriting ejemplo.txt


In [ ]:
!cat ejemplo.txt

Hola a todos


In [ ]:
!cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


In [ ]:
!lscpu

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:            0
CPU MHz:             2199.998
BogoMIPS:            4399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            56320K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_sin

# Montar drive

In [60]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
https://github.com/OneDrive/onedrive-sdk-python

# Diferencias entre listas y tuplas

Las listas con corchete ([]) son mutables, es decir podemos modificar sus valores

In [ ]:
lista = [2, 3, 5]

In [ ]:
lista

[2, 3, 5]

In [ ]:
lista[0] = "Hola"

In [ ]:
lista

['Hola', 3, 5]

Las tuplas contiene elementos y esta lista es inmutable (())

In [ ]:
tupla = (3, 6, 50)
print(tupla[0])

3


In [ ]:
lista = [3, 4]
tupla = (lista, 3)
tupla

([3, 4], 3)

In [ ]:
lista[0] = 5
tupla

([5, 4], 3)

Note que la siguiente modificacion genera un error ya que la tupla es inmutable

In [ ]:
tupla[0] = "hola"

TypeError: ignored

Cuando una función retorna varios elementos, Python devuelve una tupla de esos elementos

In [ ]:
def retorna_varios_elementos():
  return "hola", "a todos"
type(retorna_varios_elementos())

tuple

In [ ]:
def retorna_varios_elementos():
  return "hola", 5

In [ ]:
retorna_varios_elementos()

('hola', 5)

In [ ]:
type(retorna_varios_elementos())

('hola', 5)

In [ ]:
lista = list(retorna_varios_elementos())
lista[0] = 3
lista

[3, 'a todos']

Cualquier lista o tupla puede ser desempaquetada

In [ ]:
a, b, c = [0,4,3] # el igual funciona como una función de desempaquetado
print(a,b,c)

0 4 3


In [ ]:
a, *b = (0,4,3) # star operator de python
print(a,b)

0 [4, 3]


Si una función retorna varios elementos en forma de tupla, los podemos desempaquetar con ayuda de la igualdad

In [ ]:
x, y = retorna_varios_elementos() # desempaquetar

In [ ]:
x

'hola'

In [ ]:
y

'a todos'

In [ ]:
print(x, y)

hola a todos


In [ ]:
def retorna_varios_elementos():
  return "hola", 5, 34

In [ ]:
retorna_varios_elementos()

('hola', 5, 34)

In [ ]:
def retorna_varios_elementos():
  return "hola", 5, 34, 98, 100

El guion funciona como un elemento descartable

In [ ]:
a, _, _, b, _ = retorna_varios_elementos()

In [ ]:
_

100

In [ ]:
a

'hola'

In [ ]:
b

98

# Funciones con argumentos

Puedo crear una función que acepte varios valores

In [ ]:
def funcion(c):
  print(type(c))
  print(c)

In [ ]:
funcion(2)

<class 'int'>
2


In [ ]:
funcion(3, 3, 2, 2)

TypeError: funcion() takes 1 positional argument but 4 were given

En el caso de querer tener una función que me acepte 0 o varios elementos, utilizaremos el operador estrella (star operator)

In [ ]:
def funcion(*c):
  print(type(c))
  print(c)

funcion()
funcion(3)
funcion(3, 3, 2, 2, 5)

<class 'tuple'>
()
<class 'tuple'>
(3,)
<class 'tuple'>
(3, 3, 2, 2, 5)


Podemos tener argumentos que son obligatorios, y otros que son opcionales

In [ ]:
def funcion(ele1, ele2, *resto_de_elementos):
  print(f"ele1 = {ele1}") # esto se conoce como un f-string
  print(f"ele2 = {ele2}")
  print(f"resto_de_elementos = {resto_de_elementos}")

Una función que no retorna nada, por defecto retorna un objeto de tipo NoneType

In [ ]:
valor_retornado = funcion(3)
print(type(valor_retornado))

TypeError: funcion() missing 1 required positional argument: 'ele2'

In [ ]:
valor_retornado = funcion(3.333, 5)
print(type(valor_retornado))

ele1 = 3.333
ele2 = 5
resto_de_elementos = ()
<class 'NoneType'>


In [ ]:
funcion(3, 5, 8, 9, 3)

ele1 = 3
ele2 = 5
resto_de_elementos = (8, 9, 3)


In [ ]:
def funcion(elem1, elem2, *resto_de_elementos, param1=3, param2=4, **kwargs):
  print(f"elem1: {elem1} elem2: {elem2}")
  print(f"resto_de_elementos: {resto_de_elementos}")
  print(f"param1: {param1} param2: {param2}")
  print(f"kwargs: {kwargs}")

funcion(2, 3, 5, 2, 1, 5, param3="param3", param4="param4")

SyntaxError: invalid syntax (<ipython-input-39-691f12dace27>, line 1)

# Operador Zip

El operador zip o cremallera nos permite juntar dos arreglos elemento a elemento

In [ ]:
lista_1 = ["Alejandro", "Daniela", "Diego", "Pedro", "Armando"]
lista_2 = [6, 58, 7, 8, 1]
lista_3 = ["Colombia", "Argentina", "Peru", "Costa Rica"]

In [ ]:
list(zip(lista_1, lista_2, lista_3))

[('Alejandro', 6, 'Colombia'),
 ('Daniela', 58, 'Argentina'),
 ('Diego', 7, 'Peru'),
 ('Pedro', 8, 'Costa Rica')]

In [ ]:

# zip = [('Alejandro', 6), ('Daniela', 58), ('Diego', 7), ('Pedro', 8), ('Armando', 1)]
for x in zip(lista_1, lista_2):
  print(type(x))
  print(x)

<class 'tuple'>
('Alejandro', 6)
<class 'tuple'>
('Daniela', 58)
<class 'tuple'>
('Diego', 7)
<class 'tuple'>
('Pedro', 8)
<class 'tuple'>
('Armando', 1)


Si recuerdan yo puedo desempaquetar tuplas

In [ ]:
# zip = [('Alejandro', 6), ('Daniela', 58), ('Diego', 7), ('Pedro', 8), ('Armando', 1)]
for nombre, edad in zip(lista_1, lista_2): # desempaquetamos tuplas
  print("nombre = ", nombre, " edad = ", edad)
  print("nombre = %s edad %s" % (nombre, edad))
  print(f"tipo nombre = {type(nombre)}, tipo edad = {type(edad)}")
  print(f"nombre = {nombre}, edad = {edad}")

nombre =  Alejandro  edad =  6
nombre = Alejandro edad 6
tipo nombre = <class 'str'>, tipo edad = <class 'int'>
nombre = Alejandro, edad = 6
nombre =  Daniela  edad =  58
nombre = Daniela edad 58
tipo nombre = <class 'str'>, tipo edad = <class 'int'>
nombre = Daniela, edad = 58
nombre =  Diego  edad =  7
nombre = Diego edad 7
tipo nombre = <class 'str'>, tipo edad = <class 'int'>
nombre = Diego, edad = 7
nombre =  Pedro  edad =  8
nombre = Pedro edad 8
tipo nombre = <class 'str'>, tipo edad = <class 'int'>
nombre = Pedro, edad = 8
nombre =  Armando  edad =  1
nombre = Armando edad 1
tipo nombre = <class 'str'>, tipo edad = <class 'int'>
nombre = Armando, edad = 1


In [ ]:
# zip = [(4,6),(58,58),(7,7),(5,8),(1,1)]
for x, _ in zip(lista_1, lista_2): # Puedo desempaquetar y descartar alguno elementos
  print(type(x))
  print(x)

<class 'int'>
4
<class 'int'>
58
<class 'int'>
7
<class 'int'>
5
<class 'int'>
1


In [ ]:
a, _ = [43, 2] # Desempaquetar obviando un valor
a

43

In [ ]:
lista_2

[6, 58, 7, 8, 1]

In [ ]:
import numpy as np

In [ ]:
arreglo_2 = np.array(lista_2)

In [ ]:
list(zip(lista_1, arreglo_2[[3,0,1,4,2]], lista_2, lista_2))

[('Alejandro', 8, 6, 6),
 ('Daniela', 6, 58, 58),
 ('Diego', 58, 7, 7),
 ('Pedro', 1, 8, 8),
 ('Armando', 7, 1, 1)]

# **Colección por comprension**

In [ ]:
print(range(10))

range(0, 10)


El siguiente ejemplo muestra un for normal

In [ ]:
lista = []
for i in range(10):
  lista.append(i * i)
print(lista)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


El siguiente ejemplo muestra una lista por comprensión

In [ ]:
print([i*i for i in range(10)]) # Listas por comprensión

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
print(tuple((i*i for i in range(10)))) # tuplas por comprensión

(0, 1, 4, 9, 16, 25, 36, 49, 64, 81)


In [ ]:
print({i for i in range(10)}) # conjuntos por comprensión

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
print({str(i):i for i in range(10)}) # diccionarios por comprensión

{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9}


# Listas

In [ ]:
lista = list(range(20))
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
lista = lista[:-1] # remove el último valor de la lista
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


In [ ]:
lista[::-1]

[18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
lista.remove(9)
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18]


La siguiente instrucción me permite definir una lista por comprensión con un if anidado

In [ ]:
lista = list(range(20))
print([x for x in lista if x != 9])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
lista = list(range(20))
print([x for x in lista if x%2==0])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
lista = list(range(20))
print([(x, x*x,x**3,x**(1/2)) for x in lista if x%2==0])

[(0, 0, 0, 0.0), (2, 4, 8, 1.4142135623730951), (4, 16, 64, 2.0), (6, 36, 216, 2.449489742783178), (8, 64, 512, 2.8284271247461903), (10, 100, 1000, 3.1622776601683795), (12, 144, 1728, 3.4641016151377544), (14, 196, 2744, 3.7416573867739413), (16, 256, 4096, 4.0), (18, 324, 5832, 4.242640687119285)]


La primera parte de un filtro recibe una función. Esta función debe devolver un valor booleano

In [ ]:
def par(x):
  return x%2 == 0

In [ ]:
list(filter(par, lista))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
lista2 = [3,5,8,9,2,0]

In [ ]:
list(filter(par, lista2))

[8, 2, 0]

In [ ]:
list(zip(lista_1, lista_2))[3][1]

# Explicación de conjuntos

In [62]:
lista1 = ["joseph", "alejandro", "daniela", "andrea", "steve", "joseph"]
lista2 = ["alejandro", "steve", "pepe", "pepe"]

Queremos obtener un listado sin repeticiones de elementos de la lista 1

In [63]:
print(set(lista1)) # set es conjunto en inglés

{'alejandro', 'joseph', 'andrea', 'daniela', 'steve'}


Podriamos hacer lo mismo, pero con la lista dos

In [64]:
print(set(lista2))

{'alejandro', 'steve', 'pepe'}


Que elementos son únicos de la lista1 que no estan en la lista2

In [ ]:
print(set(lista1) - set(lista2))

{'joseph', 'daniela', 'andrea'}


In [65]:
print(set(lista1))
print(set(lista2))
print(set(lista1).union(set(lista2)))

{'alejandro', 'joseph', 'andrea', 'daniela', 'steve'}
{'alejandro', 'steve', 'pepe'}
{'alejandro', 'daniela', 'joseph', 'steve', 'andrea', 'pepe'}


In [66]:
print(set(lista1))
print(set(lista2))
print(set(lista1).intersection(set(lista2)))

{'alejandro', 'joseph', 'andrea', 'daniela', 'steve'}
{'alejandro', 'steve', 'pepe'}
{'alejandro', 'steve'}


In [ ]:
for elemento in set(lista1).intersection(set(lista2)):
  print(elemento)

steve
alejandro


In [67]:
lista = list(set(lista1).intersection(set(lista2)))
lista.sort()
lista

['alejandro', 'steve']

# Obtener elementos repetidos de una lista

In [69]:
from collections import Counter

lista = Counter(lista1).items()
print(lista)
[elemento for elemento in lista if elemento[1] > 1]

dict_items([(3, 1), (2, 2), (45, 1)])


[(2, 2)]

# Funciones como argumentos y Lambda functions

Definamos primero una función con nombre llamada `funcion_suma`

In [70]:
def funcion_suma(a, b):
  return a + b

In [71]:
funcion_suma(5, 10)

15

In [72]:
def funcion_multiplicacion(a, b):
  return a * b

In [73]:
funcion_multiplicacion(5, 10)

50

A continuación definimos una función que recibe otra función como argumento

In [ ]:
def funcion_todera(funcion_a_aplicar, numero_1, numero_2):
  return funcion_a_aplicar(numero_1, numero_2)

In [ ]:
funcion_todera(funcion_suma, 10, 2 ) # función como argumento

12

In [ ]:
funcion_todera(funcion_multiplicacion, 10, 2)

20

In [ ]:
funcion_todera(lambda x,y : x+y, 10, 2) # función sin nombre, o función lambda

12

In [77]:
!pip install tutor

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 kB 1.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 21.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 85.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 86.0 MB/s eta 0:00:00
  Created wheel for tutor: filename=tutor-17.0.2-py3-none-any.whl size=142309 sha256=9ed57708fe4b6d1d8b5c48d0fa93dc59dd36770f2e376c2b5761946abbd96b60
  Stored in directory: /root/.cache/pip/wheels/bf/79/0e/885d2f1d162d5d9319c018f79efca17a5b01d03a08856aa5a6
Successfully built tutor


In [ ]:
funcion_todera( lambda x,y : x*y, 10, 2)

20

In [ ]:
funcion_todera(lambda x,y : x/y, 10, 2)

5.0

In [ ]:
def funcion_todera(funcion_a_aplicar, *operadores):
  return funcion_a_aplicar(operadores)

In [ ]:
funcion_todera(lambda x : sum(x), 3, 5, 1)

9

In [ ]:
lista = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
def elevar_cubo(x):
  return x ** 3

La función map sirve para iterar sobre una lista de datos y aplicar una función a cada dato de la lista

In [ ]:
list(map(elevar_cubo, lista))

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [ ]:
list(map(elevar_cubo, np.array(range(10))))

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

Cuando el arreglo es un arreglo bidimensional de python, ya no funciona

In [ ]:
list(map(elevar_cubo, np.ones((5,5))))

[array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.])]

In [ ]:
list(map(lambda x: x**6, lista))

[0, 1, 64, 729, 4096, 15625, 46656, 117649, 262144, 531441]

In [ ]:
pseudo_diccionario = [["nombre", "Joseph"], ["nombre", "Joseph"], ["nombre", "Joseph"]]

In [ ]:
list(map(lambda x: print(x[0], " ", x[1]),  pseudo_diccionario))

nombre   Joseph
nombre   Joseph
nombre   Joseph


[None, None, None]

In [ ]:
lista=[4,8,10]
list(map(lambda x: x-2, lista))

[2, 6, 8]

In [ ]:
matriz_1

NameError: ignored

In [ ]:
list(map(elevar_cubo, matriz_1))

[array([ 0,  1,  8, 27]),
 array([ 64, 125, 216, 343]),
 array([ 512,  729, 1000, 1331]),
 array([1728, 2197, 2744, 3375])]

In [ ]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

La primera operación de un filtro debe devolver un booleano

In [ ]:
list(filter(lambda x: x>3, list(range(9))))

[4, 5, 6, 7, 8]

In [ ]:
lista = np.arange(10)
lista

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
lista[lista>3]

array([4, 5, 6, 7, 8, 9])

In [ ]:
list(filter(lambda x: print(x), {"a": 3, "b": 6}.items()))

('a', 3)
('b', 6)


[]

In [ ]:
list(filter(lambda x: x[1]>3, {"a": 3, "b": 6}.items()))

[('b', 6)]

# Descargar archivos desde drive

Gdown -> descarga de archivos desde drive

In [ ]:
!gdown --id 1aUi2r9_abPE8wV3Hf-WWdaWtsVCXw8ca

Downloading...
From: https://drive.google.com/uc?id=1aUi2r9_abPE8wV3Hf-WWdaWtsVCXw8ca
To: /content/back.gif
100% 1.83M/1.83M [00:00<00:00, 58.3MB/s]


# Operadores ternarios

In [ ]:
variable_1 = 20
if variable_1 > 40:
  print("mayor a 40")
else:
  print("menor a 40")

menor


In [ ]:
variable_1 = 20
print("mayor") if variable_1 > 40 else print("menor")

menor


In [ ]:
cadena = "mayor" if variable_1 > 40 else "menor"
cadena

'menor'

# Comprensión de listas

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(3, 10))

[3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(3, 10, 2))

[3, 5, 7, 9]

In [ ]:
lista = []
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
lista = []
for i in range(10):
  lista.append(i)

lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.array(lista)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
lista = [variable **3 for variable in range(10)]

In [ ]:
lista

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [ ]:
lista_1 = np.array(range(9)).reshape((3,3))
lista_2 = np.array(range(9)).reshape((3,3))*2

In [ ]:
for x, y  in zip(lista_1.ravel(), lista_2.ravel()):
  print("x", x)
  print("y",y)

x 0
y 0
x 1
y 2
x 2
y 4
x 3
y 6
x 4
y 8
x 5
y 10
x 6
y 12
x 7
y 14
x 8
y 16


In [ ]:
lista_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
lista_2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
lista_1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Filter

In [ ]:
lista = [3, 4, 5, 6]

In [ ]:
def menoresACuatro(x):
  return x<=4

list(filter(menoresACuatro, lista))

In [ ]:
list(filter(lambda x: x<=4, lista)) # la función del filter siempre debe ser un booleano

[3, 4]

In [ ]:
edades = [38, 45, 22, 10]

In [ ]:
def filtrar_edades(edad):
  return edad <= 25

In [ ]:
edades_filtradas = []
for edad in edades:
  persona_aceptada = filtrar_edades(edad) # función de dedición
  if(persona_aceptada): # dedición
    edades_filtradas.append(edad) # agregamos el elemento que cumple la condición

print(edades_filtradas)

[22, 10]


In [ ]:
list(filter(filtrar_edades, edades))

[22, 10]

In [ ]:
list(filter(lambda edad: edad < 25, edades))

[22, 10]

# Funciones

In [ ]:
def suma(a, b):
  return a + b

In [ ]:
type(suma(4, 3)) # Desempaquetamiento

int

In [ ]:
def suma_y_resta(a, b):
  return a + b, a - b

In [ ]:
suma_y_resta(3, 5)

(8, -2)

In [ ]:
type(suma_y_resta(3, 5))

tuple

In [ ]:
def suma_y_resta(a, b):
  return (a + b, a - b)

In [ ]:
variable = suma_y_resta(3, 5)
variable[0] = 3

TypeError: ignored

In [ ]:
def suma_y_resta(a, b):
  return [a + b, a - b]

In [ ]:
print(type(suma_y_resta(3, 5)))

<class 'list'>


# Map and Reduce

In [ ]:
edades = [38, 45, 22, 10]

In [ ]:
def extraer_decadas(edad):
  return int(edad / 10)

In [ ]:
lista_de_decadas = []
for edad in edades:
  decadas = extraer_decadas(edad)
  lista_de_decadas.append(decadas)
print(lista_de_decadas)

[3, 4, 2, 1]


In [ ]:
[extraer_decadas(edad) for edad in edades]

[3, 4, 2, 1]

In [ ]:
list(map(extraer_decadas, edades))

[3, 4, 2, 1]

In [ ]:
list(map(lambda edad: int(edad / 10), edades))

[3, 4, 2, 1]

In [ ]:
lista = [5, 6, 3, 2, 3]

In [ ]:
def cuadrado(x):
  return x*x

In [ ]:
l = []
for elemento in lista:
    l.append(cuadrado(elemento))

print(l)

[25, 36, 9, 4, 9]


In [ ]:
list(map(cuadrado, lista))

[25, 36, 9, 4, 9]

In [ ]:
list(map(lambda x: x*x, lista))

[25, 36, 9, 4, 9]

In [ ]:
print(list(map(lambda x: x*x, [23,5,3,265])))
print(list(map(lambda x: x*x, (23,5,3,265))))
print(list(map(lambda x: x*x, {23,5,3,265})))

[529, 25, 9, 70225]
[529, 25, 9, 70225]
[70225, 9, 25, 529]


In [ ]:
for elemento in {23,5,3,265,334}:
  print(elemento)

3
5
265
334
23


In [ ]:
5 in [3,5,3,2]

True

In [ ]:
dir([3,5,3,2])
[3,5,3,2].index(5)

1

In [ ]:
print(list(map(lambda item: print(item), {43: 23, 32:5})))

llave1
llave2
[None, None]


In [ ]:
def cuadrado(x):

  x = x -3
  x = x*5
  x = x /2
  return x*x


In [ ]:
list(map(cuadrado, lista))

[25.0, 56.25, 0.0, 6.25]

In [ ]:
import pandas as pd
df = pd.DataFrame([{"name": "hola", "apellido": "pepe"}])

In [ ]:
df.apply()

In [ ]:
def suma(x, y):
  return x*y

# Reduce

In [ ]:
#@markdown * **Ejecute esta celda para instalar _Python Tutor_.**
!pip3 -q install tutormagic
%load_ext tutormagic

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


The tutormagic extension is already loaded. To reload it, use:
  %reload_ext tutormagic


In [ ]:
edades = [38,45,22, 10]

In [ ]:
def funcion_suma(suma_parcial, nuevo_dato):
  return suma_parcial + nuevo_dato

In [ ]:
%%tutor -s -h 500

edades = [38,45,22, 10]

def funcion_suma(suma_parcial, nuevo_dato):
  return suma_parcial + nuevo_dato

suma = 0
for edad in edades:
  suma = funcion_suma(suma, edad)

print(suma)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
import functools
functools.reduce(funcion_suma, edades)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


115

In [ ]:
%%tutor -s -h 500
edades = [38,45,22, 10]

def funcion_multiplicacion(multiplicacion_parcial, nuevo_dato):
  return multiplicacion_parcial * nuevo_dato

multiplicacion = 1
for edad in edades:
  multiplicacion = funcion_multiplicacion(multiplicacion, edad)

print(multiplicacion)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
import functools
functools.reduce(funcion_multiplicacion, edades)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


376200

# **Funciones como argumentos**

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

def multiplicacion(num1, num2):
  return num1 * num2

def division(num1, num2):
  return num1 / num2

def elevacion(num1, num2):
  return num1 ** num2

#print(suma(multiplicacion, division, 5, 43))

#print(suma(division, multiplicacion, 5, 43))

print(suma(elevacion, multiplicacion, 5, 43))


1136868377216160297393798828340


In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2, 4) + fun2(num1, num2)

def multiplicacion(num1, num2):
  return num1 * num2

def division(num1, num2):
  return num1 / num2

suma(multiplicacion, division, 5, 43) # No se puede ya que la función 1, que le
                                      # enviamos como multiplicacion solo acepta 2 parametros,
                                      # en este caso nos genera error de posiciones de argumentos

TypeError: ignored

# **Funciones Lambda**

In [ ]:
def fun(x):
  return x+1

In [ ]:
fun(3)

4

In [ ]:
lambda x: x+1

In [ ]:
(lambda x: x+1)(3)

4

Vamos a cambiar las funciones normales de python, por sus respectivas funciones lambda, y vamos a ver en el camino como se utilizan estas funciones.

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

def multiplicacion(num1, num2):
  return num1 * num2

def division(num1, num2):
  return num1 / num2

suma(multiplicacion, division, 5, 43)

215.11627906976744

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

multiplicacion = lambda num1, num2: num1 * num2

def division(num1, num2):
  return num1 / num2

suma(multiplicacion, division, 5, 43)

215.11627906976744

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

multiplicacion = lambda num1, num2: num1 * num2

division = lambda num1, num2: num1 / num2

suma(multiplicacion, division, 5, 43)

215.11627906976744

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

division = lambda num1, num2: num1 / num2

suma(lambda num1, num2: num1 * num2, division, 5, 43)

215.11627906976744

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

suma(lambda num1, num2: num1 * num2, lambda num1, num2: num1 / num2, 5, 43)

215.11627906976744

In [ ]:
suma = lambda fun1, fun2, num1, num2 : fun1(num1, num2) + fun2(num1, num2)

suma(lambda num1, num2: num1 * num2, lambda num1, num2: num1 / num2, 5, 43)

215.11627906976744

In [ ]:
[3.5 , 5 , 6 ].apply(lambda x: x+1)

AttributeError: ignored

# Is vs ==

In [ ]:
print('Operador is')
a = 1.0
b = 1
c = 1

Operador is
False
True
True
False


In [ ]:
lista1 = [1,2,3]
lista2 = [1,2,3]

In [ ]:
print(a is b) # No tienen el mismo tipo de dato y por lo tanto son objetos distintos.

False


In [ ]:
print(a == b) # Contienen el mismo valor al verificar su igualdad.

True


In [ ]:
print(b is c) #¿en este caso b y c ocupan el mismo lugar de memoria?***

True


In [ ]:
tupla1 = (1,2,3)
tupla2 = (1,2,3)

In [ ]:
print(tupla1 is tupla2) #¿Por qué en este caso son diferentes?***

False


In [ ]:
print(tupla1 == tupla2) #¿Por qué en este caso son diferentes?***

True


In [ ]:
print(lista1 is lista2)

False


In [ ]:
print(lista1 == lista2)

True


# Generador

In [ ]:
#@markdown * **Ejecute esta celda para instalar _Python Tutor_.**
!pip3 -q install tutormagic
%load_ext tutormagic

In [ ]:
%%tutor -s -h 500

def funcion():
  yield 1
  yield 2
  yield 3


generador = funcion()
print(next(generador))
print(next(generador))
print(next(generador))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
%%tutor -s -h 500

def funcion():
  yield [[2]]
  yield [[3]]
  yield [[]]


generador = funcion()
print(next(generador))
print(next(generador))
print(next(generador))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
%%tutor -s -h 500

def funcion_parcial(dato):
  def funcion(elemento):
    return dato + elemento

  return funcion

def funcion():
  yield funcion_parcial(0)
  yield funcion_parcial(1)
  yield funcion_parcial(2)


generador = funcion()
print(next(generador)(1))
print(next(generador)(1))
print(next(generador)(1))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
generador = funcion()
print(next(generador))

1


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
generador = funcion()
print(generador.__next__())
print(generador.__next__())
print(generador.__next__())
print(generador.__next__()) # no hay mas yield

1
2
3


StopIteration: ignored

In [ ]:
generador = (i*i for i in range(10)) # tuplas por comprensión
print(generador.__next__())
print(generador.__next__())
print(generador.__next__())
print(generador.__next__())
print(generador.__next__())
print(generador.__next__())

0
1
4
9
16
25


In [ ]:
def funcion(n):
  for i in range(n):
    yield i

In [ ]:
generador = funcion(10)
generador.__next__()

0

In [ ]:
import itertools

In [ ]:
generador = (i*i for i in range(10)) # tuplas por comprensión

In [ ]:
generador, copia_generador = itertools.tee(generador)

In [ ]:
generador.__next__()

0

In [ ]:
copia_generador.__next__()

0

In [ ]:
generador.__iter__()
generador.__next__()

9

# Numpy

# Explicación de Numpy

In [ ]:
import numpy as np

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
np.ones((10,6))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((10,6)) + 6

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.]])

In [ ]:
np.zeros((10,6)) + 6

array([[6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.]])

In [ ]:
matriz = np.zeros((10,6))
matriz.fill(6)
matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.]])

In [ ]:
np.full((10,6), 6)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [ ]:
np.full((10,6,5, 10), 6).shape

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(10, 6, 5, 10)

In [ ]:
list(range(20))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
arreglo = np.array(range(20))
arreglo

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(20)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(-3, 20, 0.3)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([-3.00000000e+00, -2.70000000e+00, -2.40000000e+00, -2.10000000e+00,
       -1.80000000e+00, -1.50000000e+00, -1.20000000e+00, -9.00000000e-01,
       -6.00000000e-01, -3.00000000e-01, -1.77635684e-15,  3.00000000e-01,
        6.00000000e-01,  9.00000000e-01,  1.20000000e+00,  1.50000000e+00,
        1.80000000e+00,  2.10000000e+00,  2.40000000e+00,  2.70000000e+00,
        3.00000000e+00,  3.30000000e+00,  3.60000000e+00,  3.90000000e+00,
        4.20000000e+00,  4.50000000e+00,  4.80000000e+00,  5.10000000e+00,
        5.40000000e+00,  5.70000000e+00,  6.00000000e+00,  6.30000000e+00,
        6.60000000e+00,  6.90000000e+00,  7.20000000e+00,  7.50000000e+00,
        7.80000000e+00,  8.10000000e+00,  8.40000000e+00,  8.70000000e+00,
        9.00000000e+00,  9.30000000e+00,  9.60000000e+00,  9.90000000e+00,
        1.02000000e+01,  1.05000000e+01,  1.08000000e+01,  1.11000000e+01,
        1.14000000e+01,  1.17000000e+01,  1.20000000e+01,  1.23000000e+01,
        1.26000000e+01,  

In [ ]:
np.linspace(0, 20, num=5) # genera 100 números entre 0 y 20 igualmente distribuidos

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.linspace?

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<frozen importlib._bootstrap>:914: ImportWarning: APICoreClientInfoImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _OpenCVImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _AltairImportHook.find_spec() not found; falling back to find_module()


In [ ]:
np.linspace(0, 20, num=5, endpoint = False) # genera 100 números entre 0 y 20 igualmente distribuidos

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 0.,  4.,  8., 12., 16.])

In [ ]:
arreglo = np.arange(20)
arreglo

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arreglo.shape

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(20,)

Siempre nos devuelve una tupla en la que cada dato de la tupla corresponde a una dimensión del arreglo

In [ ]:
arreglo.reshape((4, 5))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arreglo.reshape((4, 5)).reshape((2,2,5))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [ ]:
matriz = arreglo.reshape((2,10))
matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
matriz[0, 3]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


3

In [ ]:
matriz[1, 6]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


16

In [ ]:
matriz[:, 2: 6]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 2,  3,  4,  5],
       [12, 13, 14, 15]])

In [ ]:
tensor = arreglo.reshape((2,2,5))
tensor

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [ ]:
tensor[0, 1, 3]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


8

## Indexado elegante

In [ ]:
matriz = arreglo.reshape((4, 5))
matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
matriz[:, [1, 3]]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [ ]:
matriz[1:3, [1, 3]]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 6,  8],
       [11, 13]])

In [ ]:
matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
matriz[[0,1], :] = matriz[[1,0],:] # Indexado elegante
matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
5 % 2

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


1

In [ ]:
5 - 5 // 2 * 2

1

In [ ]:
matriz % 2

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [ ]:
matriz_impar = (matriz % 2).astype(bool)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
matriz_impar == True

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [ ]:
matriz_impar = (matriz % 2).astype(str)
matriz_impar

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([['1', '0', '1', '0', '1'],
       ['0', '1', '0', '1', '0'],
       ['0', '1', '0', '1', '0'],
       ['1', '0', '1', '0', '1']], dtype='<U21')

In [ ]:
matriz_impar[matriz_impar == "1"] = "impar"
matriz_impar[matriz_impar == "0"] = "par"
matriz_impar

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([['impar', 'par', 'impar', 'par', 'impar'],
       ['par', 'impar', 'par', 'impar', 'par'],
       ['par', 'impar', 'par', 'impar', 'par'],
       ['impar', 'par', 'impar', 'par', 'impar']], dtype='<U21')

In [ ]:
~(matriz % 2).astype(bool)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [ ]:
matriz[(matriz % 2).astype(bool)]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 5,  7,  9,  1,  3, 11, 13, 15, 17, 19])

In [ ]:
matriz[(matriz % 2 == 0).astype(bool)]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 6,  8,  0,  2,  4, 10, 12, 14, 16, 18])

In [ ]:
matriz[(matriz % 2).astype(bool) == False]

array([10, 12, 14, 16, 18,  0,  2,  4,  6,  8])

In [ ]:
arreglo.reshape((2, -1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
arreglo.reshape((3, -1))

ValueError: ignored

In [ ]:
arreglo.reshape((2, 2, 5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [ ]:
troceado = arreglo[0:18] # troceado de listas
cubo = troceado.reshape((2,3,3))
cubo

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[[ 5,  6,  7],
        [ 8,  9,  0],
        [ 1,  2,  3]],

       [[ 4, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [ ]:
cubo.ravel?

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
cubo.flatten()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 5,  6,  7,  8,  9,  0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
cubo.flatten?

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
matriz = np.arange(20).reshape((4,5))
#display(matriz)
print(matriz)
print(matriz.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


## Ravel

In [ ]:
matriz.ravel()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([ 5,  6,  7,  8,  9,  0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Squeeze

In [ ]:
agregar_dimension = arreglo.reshape((4, 1, -1))
agregar_dimension.shape

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(4, 1, 5)

In [ ]:
agregar_dimension

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[[ 5,  6,  7,  8,  9]],

       [[ 0,  1,  2,  3,  4]],

       [[10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19]]])

In [ ]:
np.squeeze(agregar_dimension, axis=1)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.squeeze(agregar_dimension, axis=1).shape

(4, 5)

## Operaciones matriz

In [ ]:
matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
matriz[1,2]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


2

In [ ]:
matriz[1, 2] = 999
matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[  5,   6,   7,   8,   9],
       [  0,   1, 999,   3,   4],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [ ]:
matriz[:,:]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[  5,   6,   7,   8,   9],
       [  0,   1, 999,   3,   4],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [ ]:
matriz[0,:]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([5, 6, 7, 8, 9])

In [ ]:
matriz[0, :] = [10,20,30,40,50]
matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[ 10,  20,  30,  40,  50],
       [  0,   1, 999,   3,   4],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [ ]:
matriz[:,0]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([10,  0, 10, 15])

In [ ]:
matriz_1 = matriz[:,0][:, np.newaxis]
matriz_1

array([[10],
       [ 5],
       [10],
       [15]])

In [ ]:
matriz_1.shape

(4, 1)

In [ ]:
matriz[:,0].shape

(4,)

In [ ]:
matriz_2 = matriz[:,0][np.newaxis, :]
matriz_2

array([[10,  5, 10, 15]])

In [ ]:
matriz_2.shape

(1, 4)

In [ ]:
matriz[:,0].reshape((1,4))

array([[10,  5, 10, 15]])

In [ ]:
matriz[:,0].reshape((1,4)).shape

(1, 4)

In [ ]:
matriz = matriz.reshape((5, -1))
matriz

array([[ 10,  20,  30,  40],
       [ 50,   5,   6, 999],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19]])

In [ ]:
matriz.dtype

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


dtype('int64')

In [ ]:
matriz2 = np.zeros((6, 4))
matriz2[:5, :] = matriz

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


ValueError: ignored

In [ ]:
matriz2[5,: ] = matriz2[4, :] * 4
matriz2

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
matriz2.dtype

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


dtype('float64')

In [ ]:
matriz

array([[ 10,  20,  30,  40],
       [ 50,   5,   6, 999],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19]])

In [ ]:
media = matriz.mean(axis=0)
media[np.newaxis, : ]

array([[ 19.2,  12.8,  15.6, 216.8]])

In [ ]:
np.vstack((matriz, media[np.newaxis,: ]))

array([[ 10. ,  20. ,  30. ,  40. ],
       [ 50. ,   5. ,   6. , 999. ],
       [  8. ,   9. ,  10. ,  11. ],
       [ 12. ,  13. ,  14. ,  15. ],
       [ 16. ,  17. ,  18. ,  19. ],
       [ 19.2,  12.8,  15.6, 216.8]])

In [ ]:

matriz[:,0].reshape((1, 4))

array([[10,  5, 10, 15]])

In [ ]:
matriz[0:2,:]

array([[ 10,  20,  30,  40,  50],
       [  5,   6, 999,   8,   9]])

In [ ]:
%timeit sum(range(1_000_000_000)) # timeit es un magico de jupyter

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


26.8 s ± 1.68 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit np.arange(0,1_000_000_000,1).sum() # implementación en lenguaje C

1 loop, best of 5: 1.97 s per loop


In [ ]:
matriz.sum(axis=1) #Sume por columnas

array([  10, 1027,   60,   85])

In [ ]:
matriz.sum(axis=0) #Sume por filas

array([  30,   34, 1030,   42,   46])

In [ ]:
matriz[:, 3:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [ ]:
matriz[:, :3]

array([[  0,   1,   2],
       [  5,   6, 999],
       [ 10,  11,  12],
       [ 15,  16,  17]])

In [ ]:
matriz[0, :] = 3
matriz

array([[  3,   3,   3,   3,   3],
       [  5,   6, 999,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [ ]:
matriz[:, 1:3] = matriz[:, 1:3] * 3
matriz

array([[   3,   27,   27,    3,    3],
       [   5,   54, 8991,    8,    9],
       [  10,   99,  108,   13,   14],
       [  15,  144,  153,   18,   19]])

In [ ]:
for i in range(matriz.shape[0]):
  matriz[i, i] = 6

In [ ]:
matriz

array([[   6,   27,   27,    3,    3],
       [   5,    6, 8991,    8,    9],
       [  10,   99,    6,   13,   14],
       [  15,  144,  153,    6,   19]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arreglo = np.ones((4,4))
arreglo + np.eye(4)

array([[2., 1., 1., 1.],
       [1., 2., 1., 1.],
       [1., 1., 2., 1.],
       [1., 1., 1., 2.]])

In [ ]:
tensor = np.ones((4,5,3))
#display(tensor)
print(tensor)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
tensor[3,:,:] = tensor[3,:,:] * 4

In [ ]:
tensor

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

In [ ]:
tensor[3,:,:].shape

(5, 3)

In [ ]:
(tensor[1,:,:] * 4 ).shape

(5, 3)

In [ ]:
slice_tensor = tensor[1,:,:] * 4
slice_tensor

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
tensor

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

In [ ]:
tensor[::3,:,:]

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

In [ ]:
matriz_1 = np.ones((4,4)) * 6
matriz_1

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
matriz_2 = np.ones((4,4)) * 2.5
matriz_2

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [ ]:
matriz_1 * matriz_2

array([[15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.]])

In [ ]:
np.ones(3) * np.ones(4) # dotwise

ValueError: ignored

In [ ]:
np.dot(matriz_1, matriz_2).flatten()

array([60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60.,
       60., 60., 60.])

In [ ]:
matriz_1 @ matriz_2

array([[60., 60., 60., 60.],
       [60., 60., 60., 60.],
       [60., 60., 60., 60.],
       [60., 60., 60., 60.]])

In [ ]:
[0,1,2,3,4,5,6,7,8,9,10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
lista = []
#[]
for i in range(11):
  lista.append(i)

lista

In [ ]:
[x**2 for x in range(11)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
[2 for y in range(11)]

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [ ]:
[i for i in range(5,11,2)]

[5, 7, 9]

In [ ]:
lista_inicial = list(range(16))
arreglo_inicial = np.array(lista_inicial)
arreglo_inicial.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
matriz_1 = np.array(list(range(16))).reshape((4,4))
display(matriz_1)
matriz_2 = np.array(range(16)).reshape((4,4)) * 2
display(matriz_2)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
#np.array(list(range(16))).reshape((4,5))

In [ ]:
matriz_1 * matriz_2

array([[  0,   2,   8,  18],
       [ 32,  50,  72,  98],
       [128, 162, 200, 242],
       [288, 338, 392, 450]])

In [ ]:
np.dot(matriz_1, matriz_2)

array([[ 112,  124,  136,  148],
       [ 304,  348,  392,  436],
       [ 496,  572,  648,  724],
       [ 688,  796,  904, 1012]])

In [ ]:
matriz_2.sum()

40.0

In [ ]:
matriz_2.sum(axis=0)

array([10., 10., 10., 10.])

In [ ]:
matriz_2.sum(axis=1)

array([10., 10., 10., 10.])

## Suma por eje

In [ ]:
matriz = np.array([[3,8,9], [10,15,3], [2,7,6]])
matriz

array([[ 3,  8,  9],
       [10, 15,  3],
       [ 2,  7,  6]])

In [ ]:
matriz.sum()

63

In [ ]:
matriz.sum(axis=0)

array([15, 30, 18])

In [ ]:
matriz.sum(axis=1)

array([20, 28, 15])

## Shape de matrices de numpy

In [ ]:
matriz = np.ones((3,4))
type(matriz.shape)

tuple

In [ ]:
M , N = matriz.shape

In [ ]:
print(M, N)

3 4


## Desviación estandar

In [ ]:
import numpy as np

In [ ]:
arreglo = np.array([3, 5, 6, 2])
arreglo

array([3, 5, 6, 2])

In [ ]:
arreglo.shape

(4,)

In [ ]:
np.sqrt(((arreglo - arreglo.mean())**2).sum()/arreglo.shape[0])

1.5811388300841898

In [ ]:
arreglo.std()

1.5811388300841898

In [ ]:
matriz = np.array([[3, 5, 6, 2], [5,2,3,32]])
matriz

array([[ 3,  5,  6,  2],
       [ 5,  2,  3, 32]])

In [ ]:
matriz.shape

(2, 4)

In [ ]:
matriz.std(axis=0)

array([ 1. ,  1.5,  1.5, 15. ])

In [ ]:
matriz.std(axis=1)

array([ 1.58113883, 12.45993579])

In [ ]:
matriz_ravel = matriz.ravel()
matriz_ravel

array([ 3,  5,  6,  2,  5,  2,  3, 32])

In [ ]:
desviacion_estandar = np.sqrt(((matriz_ravel - matriz_ravel.mean())**2).sum()/matriz_ravel.shape[0])
desviacion_estandar

9.45714015968887

In [ ]:
matriz.std()

9.45714015968887

In [ ]:
media = matriz.mean()
media

7.25

In [ ]:
tensor = np.array([[[3,4],[5,2]],[[6,2],[7,6]]])
tensor

array([[[3, 4],
        [5, 2]],

       [[6, 2],
        [7, 6]]])

In [ ]:
tensor.shape

(2, 2, 2)

1 - Pais (colombia, chile, ecuador)
2 - deportes (natacion, baloncesto, futbol)
3 - personas

In [ ]:
estatura = np.random.uniform(50, 275, size=(3, 3, 10))
estatura

array([[[ 58.63487733, 261.99402255, 108.83215599, 250.30461648,
         208.14713384, 204.22727012, 274.63556879, 130.65845976,
          67.91637865, 206.66634986],
        [100.749655  , 260.41015021, 152.44014024, 211.16703177,
         274.25459268, 243.32659152,  79.81536008, 125.91787644,
         127.21627969, 250.83681179],
        [ 91.34749516, 186.80083586, 195.73039192, 239.8146261 ,
          98.39398108, 152.60068414, 192.1479736 ,  94.26398689,
         267.86213551, 105.56301452]],

       [[ 64.09510016,  86.8104454 , 235.5115986 ,  76.74843312,
         174.56362269, 225.15406645, 155.23118695, 209.86396591,
         133.43217677, 148.223283  ],
        [229.15186071, 261.1690858 ,  54.75264484, 109.83987175,
         260.99239438, 148.68750982, 129.4064951 , 110.74930116,
         188.50551066, 212.12895606],
        [249.87939076, 221.8945072 ,  69.54600087, 211.50219808,
         235.92434145, 146.67785781, 118.96942581,  69.78508937,
          59.74580607,  74.5

In [ ]:
estatura.std(axis=2)

array([[75.77950958, 69.33183732, 60.68008836],
       [58.46497284, 66.87201154, 73.38842071],
       [72.78785219, 43.43357708, 66.21041221]])

In [ ]:
estatura.std(axis=(1, 2))

array([69.40046525, 67.36853529, 63.4661015 ])

In [ ]:
estatura.std(axis=(0, 2))

array([70.33678349, 61.22903003, 67.59654493])

In [ ]:
estatura.std()

67.31823565143253

In [ ]:
np.std(estatura)

67.31823565143253

## EJemplo de uso de tensores

Normalmente en deep learning se trabaja con arreglos de multiples dimensiones com el siguiente.

Deep Learning -> arreglos (batch_size, número_filas, número_columnas, filtro)

In [ ]:
tensor = np.random.uniform(0, 1, size=(5,5,5))
tensor

array([[[0.13055314, 0.96290789, 0.52128242, 0.80751949, 0.85589406],
        [0.16758231, 0.80763644, 0.32617004, 0.10682113, 0.1977549 ],
        [0.58575306, 0.33820385, 0.6760106 , 0.38891938, 0.44462404],
        [0.25331888, 0.48233498, 0.84584543, 0.53315992, 0.16369242],
        [0.83827874, 0.48556494, 0.09686052, 0.46855823, 0.79214269]],

       [[0.9361287 , 0.83534602, 0.89209717, 0.43492764, 0.46554444],
        [0.96247636, 0.27669695, 0.44856967, 0.85666606, 0.77707406],
        [0.48397899, 0.30494179, 0.59253569, 0.60820046, 0.37677469],
        [0.02662634, 0.38689308, 0.10064024, 0.96078657, 0.42319518],
        [0.90900483, 0.61348379, 0.8345588 , 0.00365721, 0.90097292]],

       [[0.14028534, 0.32891593, 0.64592116, 0.64527679, 0.12846033],
        [0.33349883, 0.67386269, 0.3985793 , 0.21525606, 0.74898612],
        [0.45337158, 0.92496574, 0.09930562, 0.84500111, 0.66011535],
        [0.71590093, 0.84476841, 0.96621901, 0.10895123, 0.17740176],
        [0.54724

In [ ]:
tensor[0, 4, 3]

0.4685582270432358

## Ayuda

In [ ]:
np.array?

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [ ]:
help(np.squeeze)

Help on function squeeze in module numpy:

squeeze(a, axis=None)
    Remove single-dimensional entries from the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        .. versionadded:: 1.7.0
    
        Selects a subset of the single-dimensional entries in the
        shape. If an axis is selected with shape entry greater than
        one, an error is raised.
    
    Returns
    -------
    squeezed : ndarray
        The input array, but with all or a subset of the
        dimensions of length 1 removed. This is always `a` itself
        or a view into `a`. Note that if all axes are squeezed,
        the result is a 0d array and not a scalar.
    
    Raises
    ------
    ValueError
        If `axis` is not None, and an axis being squeezed is not of length 1
    
    See Also
    --------
    expand_dims : The inverse operation, adding singleton dimensions
    reshape : Insert, remove, an

# Range

In [ ]:
range(10000000000000000000000000000000000) # lazy operation - una operación peresoza

range(0, 10000000000000000000000000000000000)

In [ ]:
list(range(10)) # range es un generador de python

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(3, 10)) # range es un generador de python

[3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(3, 10, 2)) # range es un generador de python

[3, 5, 7, 9]

# **Listas por comprension**

In [ ]:
print(range(10))

range(0, 10)


In [ ]:
lista = []
for i in range(10):
  lista.append(i * i)
print(lista)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
print([i*i for i in range(10)])

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
lista = []
for i in range(10):
  if i % 2 == 0:
    lista.append(i * i)
print(lista)

[0, 4, 16, 36, 64]


In [ ]:
print([i*i for i in range(10) if i % 2 == 0])

[0, 4, 16, 36, 64]


In [ ]:
print([[i, ((i*i)+3)/2] for i in range(10)])

[[0, 1.5], [1, 2.0], [2, 3.5], [3, 6.0], [4, 9.5], [5, 14.0], [6, 19.5], [7, 26.0], [8, 33.5], [9, 42.0]]


# Tuplas

In [ ]:
tupla = (2, 5, 8)

In [ ]:
tupla[-1] = 9

TypeError: ignored

In [ ]:
lista = list(tupla)
lista[-1] = 9
lista

[2, 5, 9]

# Diccionario por comprensión

In [ ]:
diccionario = {i:j for i,j in zip(range(10), range(10))}
diccionario

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}

In [ ]:
paises = ["bogota", "medellin", "cali"]
poblacion = [10, 6, 3]
diccionario = {ciudad: poblacion for ciudad,poblacion in zip(paises, poblacion)}
diccionario

{'bogota': 10, 'medellin': 6, 'cali': 3}

In [ ]:
list(zip(paises, poblacion))

[('bogota', 10), ('medellin', 6), ('cali', 3)]

# **Funciones como argumentos**

In [ ]:
def suma(num1, num2):
  return num1 + num2

In [ ]:
suma(3, 5)

8

In [ ]:
def operacion(fun, num1, num2):
  return fun(num1, num2)

In [ ]:
operacion(suma, 3, 5)

8

In [ ]:
def multiplicacion(num1, num2):
  return num1 * num2

In [ ]:
operacion(multiplicacion, 3, 5)

15

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

def multiplicacion(num1, num2):
  return num1 * num2

def division(num1, num2):
  return num1 / num2

def elevacion(num1, num2):
  return num1 ** num2

#print(suma(multiplicacion, division, 5, 43))

#print(suma(division, multiplicacion, 5, 43))

print(suma(elevacion, multiplicacion, 5, 43))


1136868377216160297393798828340


In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2, 4) + fun2(num1, num2)

def multiplicacion(num1, num2):
  return num1 * num2

def division(num1, num2):
  return num1 / num2

suma(multiplicacion, division, 5, 43) # No se puede ya que la función 1, que le
                                      # enviamos como multiplicacion solo acepta 2 parametros,
                                      # en este caso nos genera error de posiciones de argumentos

TypeError: ignored

# **Funciones Lambda**

In [ ]:
def fun(x):
  return x+1

In [ ]:
fun(3)

4

In [ ]:
lambda x: x+1

<function __main__.<lambda>(x)>

In [ ]:
(lambda x: x+1)(3)

4

In [ ]:
def operacion(fun, num1, num2):
  return fun(num1, num2)

In [ ]:
type(operacion)

function

In [ ]:
operacion(lambda x,y: x+y, 3, 5)

8

In [ ]:
operacion(lambda x,y: x/y, 10, 2)

5.0

In [ ]:
operacion(lambda x,y: (x+5) ** (y+2), 10, 5)

170859375

In [ ]:
operacion(lambda x,y: [x**2, y**2, x**2+y**2], 10, 5)

[100, 25, 125]

In [ ]:
operacion(lambda x,y: [x**2,
                       x+232 * y,
                       y**2,
                       x**2+y**2], 10, 5)

[100, 1170, 25, 125]

Vamos a cambiar las funciones normales de python, por sus respectivas funciones lambda, y vamos a ver en el camino como se utilizan estas funciones.

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

def multiplicacion(num1, num2):
  return num1 * num2

def division(num1, num2):
  return num1 / num2

suma(multiplicacion, division, 5, 43)

215.11627906976744

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

multiplicacion = lambda num1, num2: num1 * num2

def division(num1, num2):
  return num1 / num2

suma(multiplicacion, division, 5, 43)

215.11627906976744

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

multiplicacion = lambda num1, num2: num1 * num2

division = lambda num1, num2: num1 / num2

suma(multiplicacion, division, 5, 43)

215.11627906976744

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

division = lambda num1, num2: num1 / num2

suma(lambda num1, num2: num1 * num2, division, 5, 43)

215.11627906976744

In [ ]:
def suma(fun1, fun2, num1, num2):
  return fun1(num1, num2) + fun2(num1, num2)

suma(lambda num1, num2: num1 * num2, lambda num1, num2: num1 / num2, 5, 43)

215.11627906976744

In [ ]:
suma = lambda fun1, fun2, num1, num2 : fun1(num1, num2) + fun2(num1, num2)

suma(lambda num1, num2: num1 * num2, lambda num1, num2: num1 / num2, 5, 43)

215.11627906976744

In [ ]:
[3.5 , 5 , 6 ].apply(lambda x: x+1)

AttributeError: ignored

# Is vs ==

In [ ]:
print('Operador is')
a = 1.1 # esto es un decimal
b = 1   # esto es un entero
c = 1
d = 1.0

Operador is


In [ ]:
print(a is b) # No tienen el mismo tipo de dato y por lo tanto son objetos distintos.

False


In [ ]:
print(a == b) # Contienen el mismo valor al verificar su igualdad.

False


In [ ]:
print(b is c) #¿en este caso b y c ocupan el mismo lugar de memoria?***

True


In [ ]:
tupla1 = (1,2,3)
tupla2 = (1,2,3)

In [ ]:
print(tupla1 is tupla2) #¿Por qué en este caso son diferentes?***

False


In [ ]:
print(tupla1 == tupla2) #¿Por qué en este caso son diferentes?***

True


In [ ]:
lista1 = [1,2,3]
lista2 = [1,2,3]

In [ ]:
print(lista1 is lista2)

False


In [ ]:
print(lista1 == lista2)

True


# Listas de Python y arreglos de numpy

In [ ]:
lista = [23, "andrés", (1,3),  True, ["pedro", {"clave":"valor"}]]

In [ ]:
lista

[23, 'andrés', (1, 3), True, ['pedro', {'clave': 'valor'}]]

In [ ]:
import numpy as np # recuerden que el as es como un alias que se le pone a la libreria

In [ ]:
arreglo = np.array([23, "andrés", (1,3),  True, ["pedro", {"clave":"valor"}]])

<ipython-input-9-28d57ea31b1a>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arreglo = np.array([23, "andrés", (1,3),  True, ["pedro", {"clave":"valor"}]])


In [ ]:
arreglo

array([23, 'andrés', (1, 3), True, list(['pedro', {'clave': 'valor'}])],
      dtype=object)

In [ ]:
arreglo + 1

TypeError: ignored

In [ ]:
arreglo2 = np.array([3, 5, 1, 7])

In [ ]:
arreglo2.dtype

dtype('int64')

In [ ]:
arreglo2 + 1

array([4, 6, 2, 8])

In [ ]:
lista_de_ciudades = np.array(["bogota", "medellin", "cali", "cartagena"])

In [ ]:
lista_de_ciudades.dtype

dtype('<U9')

# Datos no tipados en Python

In [ ]:
dato = 3
dato + 3

6

In [ ]:
dato = "hola"
dato + "."

'hola.'

In [ ]:
arreglo = np.array([2, 4, 7])

In [ ]:
arreglo + 1

array([3, 5, 8])

In [ ]:
arreglo.dtype

dtype('int64')

In [ ]:
arreglo[-1] = "hola"

ValueError: ignored

In [ ]:
arreglo = np.array([2, 4, 7], dtype=object)

In [ ]:
arreglo.dtype

dtype('O')

In [ ]:
arreglo[-1] = "hola"

In [ ]:
arreglo

array([2, 4, 'hola'], dtype=object)

In [ ]:
arreglo + 1

TypeError: ignored

# Conexión a drive

# Operaciones con bits

In [ ]:
binario1 = 0b1
binario2 = 0b1
binario1 ^ binario2

0

# Map

In [ ]:
pedidos = [5, 6, 3, 2, 3]

In [ ]:
lista = [0,0,0,0,0]

In [ ]:
variable = 3

In [ ]:
lista[variable] = 1

In [ ]:
lista

[0, 0, 0, 1, 0]

In [ ]:
for pedido in pedidos:
  print(pedido)

5
6
3
2
3


In [ ]:
def cuadrado(x):
  return x*x

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
n = int(input())
l = []
for elemento in range(n):
  l.append(cuadrado(elemento))

l

10


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
l = []
for elemento in lista:
    l.append(cuadrado(elemento))

print(l)

[25, 36, 9, 4, 9]


In [ ]:
list(map(cuadrado, lista))

[25, 36, 9, 4, 9]

In [ ]:
list(map(lambda x: x*x, lista))

[25, 36, 9, 4, 9]

In [ ]:
print(list(map(lambda x: x*x, [23,5,3,265])))
print(list(map(lambda x: x*x, (23,5,3,265))))
print(list(map(lambda x: x*x, {23,5,3,265})))

[529, 25, 9, 70225]
[529, 25, 9, 70225]
[70225, 9, 25, 529]


In [ ]:
for elemento in {23,5,3,265,334}:
  print(elemento)

3
5
265
334
23


In [ ]:
5 in [3,5,3,2]

True

In [ ]:
dir([3,5,3,2])
[3,5,3,2].index(5)

1

In [ ]:
print(list(map(lambda item: print(item), {43: 23, 32:5})))

llave1
llave2
[None, None]


In [ ]:
def cuadrado(x):

  x = x -3
  x = x*5
  x = x /2
  return x*x


In [ ]:
list(map(cuadrado, lista))

[25.0, 56.25, 0.0, 6.25]

In [ ]:
import pandas as pd
df = pd.DataFrame([{"name": "hola", "apellido": "pepe"}])

In [ ]:
df.apply()

In [ ]:
def suma(x, y):
  return x*y

In [ ]:
import functools
functools.reduce(suma, lista)

180